name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bea94a07b8d5ed9902eb7d038ad97d5f6f43a71c8173c1974727e1ef244c7b06"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
