name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e0331d881f93a8d385f1a9e20d2305cd6fa3c166c62f5f1ebe86d84d4a87d43"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
