name = "EnhancedMC Vanilla"
author = "luciobortoletto"
version = "2.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c41d2dc9f6823604eae5ed032eb60b9959f2bed4774c045c8ff7825a649116ab"

[versions]
fabric = "0.16.9"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
